[build-system]
requires = ["hatchling>=1.18.0"]
build-backend = "hatchling.build"

[project]
name = "actions-python-github"
version = "0.1.1"
description = "Actions github lib"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
  {name = "sudosubin", email = "sudosubin@gmail.com"},
]
keywords = [
  "action",
  "ci",
  "github",
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
]
dependencies = [
  "actions-python-core>=0.1.1",
  "githubkit==0.11.0a0",
  "pydantic>=2.0.0,<3.0.0",
]

[project.urls]
Homepage = "https://github.com/actions-python/toolkit"

[tool.mypy]
ignore_missing_imports = true
namespace_packages = false

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.rye]
dev-dependencies = [
  "mypy~=1.5.1",
  "pyright~=1.1.327",
  "ruff~=0.0.291",
]

[tool.rye.scripts]
format = {chain = ["format:ruff-check .", "format:ruff-format ."]}
"format:ruff-check" = {cmd = "ruff check --fix --exit-non-zero-on-fix"}
"format:ruff-format" = {cmd = "ruff format"}
lint = {chain = ["lint:mypy", "lint:pyright", "lint:ruff-check .", "lint:ruff-format ."]}
"lint:mypy" = {cmd = "mypy ."}
"lint:pyright" = {cmd = "pyright ."}
"lint:ruff-check" = {cmd = "ruff check --exit-non-zero-on-fix"}
"lint:ruff-format" = {cmd = "ruff format --check"}
test = {cmd = "python -m unittest discover -s tests"}
