repos:
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: "v2.10.0"
    hooks:
      - id: pretty-format-toml
        args: [--autofix, --no-sort, --trailing-commas]

  - repo: local
    hooks:
      - id: format
        name: format
        entry: rye run workspaces foreach run format
        language: system
        pass_filenames: false
        types_or: [python, pyi]

      - id: lint
        name: lint
        entry: rye run workspaces foreach run lint
        language: system
        pass_filenames: false
        types_or: [python, pyi]

      - id: test
        name: test
        entry: rye run workspaces foreach run test
        pass_filenames: false
        language: system
        types_or: [python, pyi]

default_language_version:
  python: "python3.11"
