repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: rye run workspaces foreach run format
        language: system
        pass_filenames: false
        types_or: [python, pyi]

      - id: lint
        name: lint
        entry: rye run workspaces foreach run lint
        language: system
        pass_filenames: false
        types_or: [python, pyi]

      - id: pyproject-fmt
        name: pyproject-fmt
        entry: rye run pyproject-fmt
        args: [--indent, "4"]
        language: system
        files: (^|/)pyproject\.toml$
        types: [file, text, toml]

      - id: test
        name: test
        entry: rye run workspaces foreach run test
        pass_filenames: false
        language: system
        types_or: [python, pyi]
