[build-system]
requires = ["hatchling>=1.18.0"]
build-backend = "hatchling.build"

[project]
name = "actions-python"
version = "0.1.1"
description = "GitHub Actions Python Toolkit"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
  {name = "sudosubin", email = "sudosubin@gmail.com"},
]
keywords = []
classifiers = []
dependencies = []

[project.optional-dependencies]
dev = [
  "mypy~=1.5.1",
  "pre-commit>=3.4.0",
  "pyright~=1.1.327",
  "ruff~=0.0.291",
  "typer[all]>=0.9.0",
]

[tool.hatch.envs.default]
path = ".venv"
features = ["dev"]
dependencies = [
  "actions-python-core[dev]",
  "actions-python-github[dev]",
]
pre-install-commands = [
  "pip install --disable-pip-version-check --quiet -e ./packages/actions-python-core[dev] -e ./packages/actions-python-github[dev]",
]
post-install-commands = [
  "pre-commit install",
]

[tool.hatch.envs.default.scripts]
workspace = "python -m contrib.cli workspace {args}"
workspaces = "python -m contrib.cli workspaces {args}"

[tool.hatch.publish.index]
disable = true

[tool.ruff]
line-length = 88
select = ["B", "E", "F", "I", "N", "RUF"]
src = [
  "packages/*",
]

[tool.ruff.isort]
combine-as-imports = true
