name: Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  package-test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: eifinger/setup-rye@v1
        with:
          version: "0.15.2"
          enable-cache: "true"

      - name: Sync
        run: rye sync --no-lock

      - name: Test
        run: rye run test
