name: CI

on:
  push:
    branches: [main, feature/add-ci]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  package-ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: eifinger/setup-rye@v1
        with:
          version: "0.15.2"
          enable-cache: "true"

      - name: Validate
        run: |
          rye sync
          rye run pre-commit run \
            --color always \
            --show-diff-on-failure \
            --from-ref $GITHUB_FROM_SHA \
            --to-ref $GITHUB_TO_SHA
        env:
          GITHUB_FROM_SHA: ${{ github.event_name == 'push' && github.event.before || github.event.pull_request.base.sha }}
          GITHUB_TO_SHA: ${{ github.event_name == 'push' && github.event.after || github.event.pull_request.head.sha }}
