name: Deploy

on:
  push:
    branches: [main, feature/add-ci]
    paths: ["**/pyproject.toml"]
  pull_request:
    types: [opened, reopened, synchronize]
    paths: ["**/pyproject.toml"]

jobs:
  package-build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ["actions-python-core", "actions-python-github"]

    steps:
      - uses: actions/checkout@v4

      - uses: eifinger/setup-rye@v1
        with:
          version: "0.15.2"

      - name: Build package
        run: rye build
        working-directory: packages/${{ matrix.workspace }}

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: package-deploy-${{ matrix.workspace }}

  package-publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs: package-build
    permissions:
      id-token: write
    strategy:
      matrix:
        workspace: ["actions-python-core", "actions-python-github"]

    steps:
      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: package-deploy-${{ matrix.workspace }}

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
